// Copyright (c) 2017 Lanceolata

#ifndef LOG2HDFS_KAFKA_KAFKA_ERROR_H_
#define LOG2HDFS_KAFKA_KAFKA_ERROR_H_

#include <string>

#ifdef __cplusplus
extern "C" {
#endif
#include "librdkafka/rdkafka.h"
#ifdef __cplusplus
}
#endif

namespace log2hdfs {

typedef rd_kafka_resp_err_t KafkaErrorCode;

// Returns a human readable representation of a kafka error.
//
// param: err Error code to translate.
extern const std::string KafkaErrorToStr(KafkaErrorCode err);

// Returns the error code name (enum name).
//
// param: err Error code to translate
extern const std::string KafkaErrorToName(KafkaErrorCode err);

// Returns the last error code generated by a legacy API call
// in the current thread.
extern KafkaErrorCode KafkaLastError();

// Converts the system errno value errnox to a rd_kafka_resp_err_t
// error code upon failure
//
// param: errnox  System errno value to convert
extern KafkaErrorCode KafkaErrnoToError(int errnox);

extern const std::string KafkaErrnoToStr(int errnox);

// Returns the thread-local system errno
extern int KafkaErrno();

}   // namespace log2hdfs

#endif  // LOG2HDFS_KAFKA_KAFKA_ERROR_H_
